In [18]:
import numpy as np

In [19]:
"""
Input format:
- First line: n = dimension of matrix
- n line: each line has n numbers: matrix A
- 1 line: n numbers: matrix B^T
"""
matrix_A = np.loadtxt('data2.txt', usecols=range(3), dtype=np.float128)
matrix_B = np.loadtxt('data2.txt', usecols=3, dtype=np.float128)
dim = len(matrix_A)
print(matrix_A)
print(matrix_B)

[[  6.  15.  55.]
 [ 15.  55. 225.]
 [ 55. 225. 979.]]
[  76.  295. 1259.]


In [20]:
def LU_decompose(a):
    """LU decomposition
        Using Cholesky Decompose
    Args:
        a : numpy array: matrix need to decompose LU
    Returns:
        numpy array: Matrix LU
    """
    n = len(a)
    L = np.zeros([n, n], dtype=np.float16)
    for j in range(n):
        for i in range(j, n):
            # print(i, j)
            if i == j:
                tmp_sum = sum([L[i][k]**2 for k in range(0, i)])
                # print(tmp_sum, a[i][j])
                L[i][j] = np.sqrt(a[i][j] - tmp_sum)
            else:
                tmp_sum = sum([L[i][k]*L[j][k] for k in range(0, i)])
                L[i][j] = (a[i][j] - tmp_sum)/L[j][j]
    return L

matrix_L = LU_decompose(matrix_A)
print(matrix_L)

[[ 2.45   0.     0.   ]
 [ 6.125  4.18   0.   ]
 [22.45  20.94   6.04 ]]


In [21]:
# Ax = LL^T x = B
# L^T x = y, then Ly = B
y = np.zeros(dim, dtype=np.float128)
for i in range(dim):
    tmp_sum = sum(matrix_L[i][j]*y[j] for j in range(i))
    y[i] = (matrix_B[i] - tmp_sum)/matrix_L[i][i]
print(y)

[31.03030303 25.10699519  6.05971797]


In [22]:
# L^T x = y
# => Calculate bottom up
matrix_L_T = matrix_L.transpose()
x = np.zeros(dim, dtype = np.float128)
for i in range(dim-1, -1, -1):
    tmp_sum = sum(matrix_L_T[i][j] * x[j] for j in range(i+1, dim))
    x[i] = (y[i] - tmp_sum) / matrix_L_T[i][i]
print(x)

[1.01879842 0.98042794 1.00342031]
