In [2]:
import numpy as np

In [14]:
matrix_A = np.loadtxt('data2.txt', usecols = range(3), dtype = np.float64)
matrix_B = np.loadtxt('data2.txt', usecols = 3, dtype = np.float64)

In [16]:
def gauss_elim(A: np.ndarray, B: np.ndarray) -> np.ndarray:
    mA = A.copy()
    mB = B.copy()

    # First pick col to make gauss eliminating
    for j in range(len(mA)):
        # Make a[j][j] to 1
        pivot = mA[j][j]
        mA[j] /= pivot
        mB[j] /= pivot
        for i in range(j+1, len(mA)):
            pivot = mA[i][j]
            mA[i] = mA[i] + -pivot * mA[j]
            mB[i] = mB[i] + -pivot * mB[j]
        print(mA)
    return mA, mB
matrix_A1, matrix_B1 = gauss_elim(matrix_A, matrix_B)
print(matrix_A1)
print(matrix_A1[1, 0])
print(matrix_B1)


[[ 1.  1.  1.]
 [ 0. -2. -6.]
 [ 0. -3. -6.]]
[[ 1.  1.  1.]
 [-0.  1.  3.]
 [ 0.  0.  3.]]
[[ 1.  1.  1.]
 [-0.  1.  3.]
 [ 0.  0.  1.]]
[[ 1.  1.  1.]
 [-0.  1.  3.]
 [ 0.  0.  1.]]
-0.0
[ 1. -1.  2.]


In [11]:
print(matrix_A)
print(matrix_B)

[[ 1.  1.  1.]
 [ 3.  1. -3.]
 [ 1. -2. -5.]]
[ 1.  5. 10.]
