Data from this site:
https://www.maa.org/press/periodicals/loci/joma/iterative-methods-for-solving-iaxi-ibi-jacobis-method

In [2]:
import numpy as np 

In [3]:
# Ax= b
filename = 'data.txt'
matrix_A = np.loadtxt(filename, usecols = range(3), dtype=np.float128)
matrix_b = np.loadtxt(filename, usecols = 3, dtype= np.float128)

In [4]:
len_A = len(matrix_A)
matrix_B = np.zeros([len_A, len_A], dtype=np.float128)
matrix_d = np.zeros(len_A, dtype=np.float128)
for i in range(len_A):
    for j in range(len_A):
        if i != j:
            matrix_B[i,j] = -matrix_A[i,j] /matrix_A[i, i]
    matrix_d[i] = matrix_b[i]/matrix_A[i,i]

In [129]:
def seidel(A:np.ndarray, x:np.ndarray, b: np.ndarray) -> np.ndarray:
    """Gauss-Seidel method, with x = Ax + b
    Args:
        A (np.ndarray): 
        x (np.ndarray): aka x^k
        b (np.ndarray):
        Return x^(k+1) (np.ndarray)
    """
    _x = x.copy()
    for i in range(len(x)):
        tmp_sum = 0.0
        for j in range(len(x)):
            if j != i:
                tmp_sum += A[i,j] * _x[j]
            # print(f"i = {i}, j = {j}, tmp_sum = {tmp_sum}")
        _x[i] = b[i] + tmp_sum
        # print(_x)
        
    return _x

In [134]:
x = np.zeros(len_A, dtype=np.float128)
print(matrix_B)
print(matrix_d)

[[ 0.          0.25        0.25      ]
 [ 0.33333333  0.         -0.16666667]
 [ 0.14285714 -0.14285714  0.        ]]
[ 0.75        1.5        -0.85714286]


In [135]:
cnt = 0
while np.linalg.norm(np.matmul(matrix_A, x) - matrix_b, ord=np.inf) > 1e-4:
    x = seidel(matrix_B, x, matrix_d)
    # print(x)
    cnt += 1
print(f"Need {cnt} steps")
print(x)

Need 6 steps
[ 0.99999957  2.00000054 -1.00000014]
