Data from this site:
https://www.maa.org/press/periodicals/loci/joma/iterative-methods-for-solving-iaxi-ibi-jacobis-method

In [1]:
import numpy as np 

In [27]:
# Ax= b
filename = 'data.txt'
matrix_A = np.loadtxt(filename, usecols = range(3), dtype=np.float128)
matrix_b = np.loadtxt(filename, usecols = 3, dtype= np.float128)

In [34]:
def jacobi(A:np.ndarray, b: np.ndarray) -> np.ndarray:
    """Jacobi method, with x = Bx + d

    Args:
        A (np.ndarray): 
        b (np.ndarray):
        Return x_n: np.ndarray: Solution of Ax = b with error = 1e-4
    """
    len_A = len(A)
    # Just need to use 2 variable to swap.
    err = 1e-4 

    # Because A is a positive matrix -> create matrix B
    # b_{ij} = -a[i,j] / a[jj] if j != i else 0
    matrix_B = np.zeros([len_A, len_A], dtype=np.float128)
    matrix_d = np.zeros(len_A, dtype=np.float128)
    for i in range(len_A):
        for j in range(len_A):
            if i != j:
                matrix_B[i,j] = -A[i,j] /A[i, i]
        matrix_d[i] = b[i]/A[i,i]
    print(A)
    print(matrix_d)
    x_0 = np.zeros(len_A, dtype=np.float128)
    x_1 = -1*np.ones(len_A, dtype=np.float128) # Create -1 np array, just for random
    x_0, x_1 = x_1, x_0 # First swap value of 2 solution array
    print(matrix_B)
    cnt = 0
    while np.linalg.norm(x_1 - x_0) > err:
        x_0, x_1 = x_1, x_0
        x_1 = matrix_d + np.matmul(matrix_B, x_0.transpose())
        cnt += 1
        print(x_1)
    print(f"Need {cnt} steps") 
    return x_1


jacobi(matrix_A, matrix_b)

[[ 4. -1. -1.]
 [-2.  6.  1.]
 [-1.  1.  7.]]
[ 0.75        1.5        -0.85714286]
[[ 0.          0.25        0.25      ]
 [ 0.33333333  0.         -0.16666667]
 [ 0.14285714 -0.14285714  0.        ]]
[ 0.75        1.5        -0.85714286]
[ 0.91071429  1.89285714 -0.96428571]
[ 0.98214286  1.96428571 -0.99744898]
[ 0.99170918  1.99362245 -0.99744898]
[ 0.99904337  1.99681122 -1.00027332]
[ 0.99913448  1.99972668 -0.99968112]
[ 1.00001139  1.99965835 -1.0000846 ]
[ 0.99989344  2.0000179  -0.99994957]
[ 1.00001708  1.99995607 -1.00001778]
[ 0.99998457  2.00000866 -0.99999128]
Need 10 steps


array([ 0.99998457,  2.00000866, -0.99999128], dtype=float128)

In [20]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.matmul(a, b.transpose())
print(c)

32
