In [1]:
import numpy as np

In [68]:
a = np.array([[2, 1, -1], [-3,-1,2], [-2,1,2]], dtype=np.float64)
b = np.array([8,-11,-3], dtype = np.float64)
x = np.linalg.solve(a, b)


In [66]:
def Gauss(a: np.ndarray, b: np.ndarray) -> None:
    n = b.size
    for j in range(n-1): 
        for i in range(j+1, n):
            if (a[j][j] != 0):
                p = a[j][j] / a[i][j]
                a[i] = -a[i]*p + a[j]
                b[i] = -b[i]*p + b[j]

In [69]:
print(Gauss(a, b))
print(a)
print(b)


None
[[ 2.          1.         -1.        ]
 [ 0.          0.33333333  0.33333333]
 [ 0.          0.          0.16666667]]
[ 8.          0.66666667 -0.16666667]


In [70]:
def replace(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    n = b.size
    x = np.zeros(n, dtype=np.float64)
    for i in range(n-1, -1, -1):
        if i == n-1:
            x[i] = b[i]/a[i][i]
        else:
            _sum = sum(a[i][i+1:n] * x[i+1:n])
            x[i] =  (b[i] - _sum)/a[i][i]
    print(x)

    return x

In [71]:
xx = replace(a, b)

[ 2.  3. -1.]


In [38]:
tmp1 = np.array([1,2,3])
tmp2 = np.array([2,2,1])
print(tmp1 * tmp2)

[2 4 3]


In [65]:
# print(x)
# assert x == xx
type(x)

numpy.ndarray